name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-dumb-api:
    runs-on: ubuntu-latest
    env:
      REPO: "dumb-api"
      CONTEXT_PATH: "./dumb-api"
      REGISTRY: "${{ vars.REGISTRY }}"
      REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"
      REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
      DOCKERFILE: "Dockerfile"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set tags
        run: |
          if [ ${GITHUB_REF} == "refs/heads/main" ]; then
            echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
          else 
            echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build, tag, and push docker image to local registry
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.CONTEXT_PATH }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.DOCKER_IMAGE_TAG }}