name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Install Buffalo
        run: go install github.com/gobuffalo/cli/cmd/buffalo@latest

      - name: Run Tests
        working-directory: ./avalanche_spoofer
        run: buffalo test

  build-spoofer:
    needs: test
    runs-on: ubuntu-latest
    env:
      REPO: "avalanche-spoofer"
      CONTEXT_PATH: "./avalanche_spoofer"
      REGISTRY: "${{ vars.REGISTRY }}"
      REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"
      REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
      DOCKERFILE: "Dockerfile"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set tags
        run: |
          if [ ${GITHUB_REF} == "refs/heads/main" ]; then
            echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
          else 
            echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build, tag, and push docker image to local registry
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.CONTEXT_PATH }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.DOCKER_IMAGE_TAG }}